language: php
php:
    - '7.2'
    - '7.3'
before_install:
    - composer selfupdate
install:
    - composer install --prefer-dist --no-interaction $COMPOSER_FLAGS
script:
    - ls -laR src
    - ls -laR tests
    - phpunit --configuration phpunit.xml.dist --coverage-text
